name: First Workflow

on:
  push:
    branches:
      - learn/github-actions

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout-code
      uses: actions/checkout@v4

    - name: Say hello
      run: echo "Pipeline is working!"